# Generated by Django 3.2.4 on 2021-07-14 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create time')),
            ],
        ),
    ]
