# Generated by Django 3.2.4 on 2021-06-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_acution_listing_provider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acution_listing',
            new_name='Auction_listing',
        ),
    ]
