# Generated by Django 3.2.4 on 2021-06-17 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_acution_listing_auction_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='item_category', to='auctions.categories'),
        ),
    ]
