# Generated by Django 3.2.4 on 2021-06-18 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210617_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
