# Generated by Django 3.2.4 on 2021-06-19 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_listing_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='bidder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='bid_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
