# Generated by Django 3.2.4 on 2021-06-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auction_listing_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
