# Generated by Django 3.2.4 on 2021-06-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='watch_user', to='auctions.Auction_listing'),
        ),
    ]
