# Generated by Django 3.2.4 on 2021-06-21 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_comment_commenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='auctions.auction_listing'),
        ),
    ]
